name: Docker Image CI for patient service

on:
  push:
    paths:
      - 'services/patient/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'services/patient/**'
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:          
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/p-service                      
          tags: |            
            type=sha
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./services/patient
          file: ./services/patient/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}          
